version: "3.8"
services:
  client:
    tty: true
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./dimiLFM-web/:/app
  server:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./dimiLFM-server/:/app
  nginx:
    build:
      dockerfile: Dockerfile.dev
  mongo:
    ports:
      - "27017:27017"
  redis:
    ports:
      - "6379:6379"