version: "3.8"
services:
  client:
    build:
      context: ./dimiLFM-web
    volumes:
      - ./dimiLFM-web/:/app
      - /app/node_modules
    networks:
      - backend
  server:
    build:
      context: ./dimiLFM-server
    volumes:
      - ./dimiLFM-server/:/app
      - /app/node_modules
    networks:
      - backend
    depends_on:
      - mongo
      - redis
    ports:
      - "5000:8080"
  redis:
    container_name: redis
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - backend
    volumes:
      - data:/data/redis
    ports:
      - "6379:6379"
    restart: always
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "8080:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local